### ISSUE TITLE
[Feat] 게임 페이지 전환

### ISSUE THREAD

**Issue by songryu** [OnetwoGame/OneTwoGame#27]
## Background
- 게임 페이지 전환 기능 구현입니다.

## To Do
- [x] 행맨 게임으로 페이지 이동 구현하기
- [x] 로딩페이지나 애니메이션 효과 찾아보기
- [x] 행맨 게임 버튼 이동 기능 추가

**Comment by rimmiya** [comment]
이슈 닫겠습니다 ~
